version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: workflow_postgres
    environment:
      POSTGRES_DB: workflowdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Dhruva@2004
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 